apiVersion: v1
kind: Service
metadata:
  name: hello-flask
spec:
  selector:
    app: hello-flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-flask
spec:
  selector:
    matchLabels:
      app: hello-flask
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-flask
    spec:
      containers:
      - image: mynat/hello-flask:latest 
        name: hello-flask
        ports:
        - containerPort: 5000 
          name: hello-flask
