apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: mysql-exporter
  template:
    metadata:
      labels:
        k8s-app: mysql-exporter
      name: mysql-exporter
    spec:
      containers:
      - image: prom/mysqld-exporter:latest
        imagePullPolicy: "IfNotPresent"
        env:
          - name: DATA_SOURCE_NAME
            value: "exporter:exporterpassword@(mysql:3306)/"
        args:
          - "--collect.info_schema.processlist"
          - "--collect.info_schema.innodb_metrics"
          - "--collect.info_schema.tablestats"
          - "--collect.info_schema.userstats"
          - "--collect.engine_innodb_status"
          - "--collect.slave_hosts"
        name: mysql-exporter
        ports:
          - containerPort: 9104
            name: mysql-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
spec:
  ports:
  - port: 9104
    targetPort: 9104
  selector:
    app: mysql-exporter
  type: LoadBalancer
